#!/bin/sh

set -e

lb config noauto \
    --mode debian \
    --architectures amd64 \
    --distribution buster \
    −−ignore−system−defaults \
    --debian-installer false \
    --archive-areas "main contrib non-free" \
    --apt-indices false \
    --memtest none \
    −−apt−recommends false \
    −−bootloader grub \
    −−bootstrap−flavour minimal \
    −−debconf−frontend noninteractive \
    −−debconf−nowarnings true \
    −−debian−installer false \
    −−distribution CODENAME \
    −−system live \
    −−source false \
    −−source−images iso \
    −−firmware−chroot true \
    −−verbose
    "${@}"

#   --mirror-binary "http://ftp.de.debian.org/debian/" \
